CREATE TABLE [dbo].[CourseScheduled]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[Guid] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[CourseId] INT NOT NULL REFERENCES Course(Id),
	[InstructorId] INT NOT NULL REFERENCES Instructor(Id),
	[StartDate] DATETIME NOT NULL,
	[EndDate] DATETIME NOT NULL,
)
