CREATE TABLE [dbo].[Course]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[SubjectId] INT NOT NULL REFERENCES Subject(Id),
	[CourseCode] NVARCHAR(15) UNIQUE NOT NULL,
	[Name] NVARCHAR(60) NOT NULL,
)
