CREATE TABLE [dbo].[Student]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[StudentCode] NVARCHAR(15) UNIQUE NOT NULL,
	[FirstName] NVARCHAR(60) NOT NULL,
	[LastName] NVARCHAR(60) NOT NULL,
	[DateOfBirth] DATETIME NOT NULL,
)
